export const GET_LOCATIONS = 'GET_LOCATIONS';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
